# Generated by Django 5.1.4 on 2025-01-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=10)),
                ('knowledge_start_date', models.DateTimeField()),
                ('knowledge_end_date', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
